name: Node CI
on: 
  - push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make test
      - run: make lint
      - name: Upload coverage to Code Climate
        env:
          CODECLIMATE_KEY: ${{ secrets.CODECLIMATE_KEY }}
        run: |
          npm install --save-dev @codeclimate/test-reporter
          CODECLIMATE_REPO_TOKEN=${{ secrets.CODECLIMATE_KEY }} ./node_modules/.bin/codeclimate-test-reporter after-build --exit-code $?