name: Node CI
on: 
  - push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
        id: checkout
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: make install
      - run: make test
      - run: make lint
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CODECLIMATE_KEY: ${{ secrets.CODECLIMATE_KEY }}
        with:
           coverageCommand: make test-coverage
           debug: true